# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 517)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(1095, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setMaximumSize(QtCore.QSize(180, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(5, 20, 5, 20)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonChooseImage = QtWidgets.QPushButton(self.tab)
        self.pushButtonChooseImage.setObjectName("pushButtonChooseImage")
        self.verticalLayout.addWidget(self.pushButtonChooseImage)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.checkBoxLockLR = QtWidgets.QCheckBox(self.tab)
        self.checkBoxLockLR.setObjectName("checkBoxLockLR")
        self.verticalLayout.addWidget(self.checkBoxLockLR)
        self.combLineEditLabelCropLeft = QtWidgets.QHBoxLayout()
        self.combLineEditLabelCropLeft.setContentsMargins(-1, 0, -1, 0)
        self.combLineEditLabelCropLeft.setSpacing(6)
        self.combLineEditLabelCropLeft.setObjectName("combLineEditLabelCropLeft")
        self.cropLeftLabel = QtWidgets.QLabel(self.tab)
        self.cropLeftLabel.setMaximumSize(QtCore.QSize(52, 20))
        self.cropLeftLabel.setObjectName("cropLeftLabel")
        self.combLineEditLabelCropLeft.addWidget(self.cropLeftLabel)
        self.spinBoxCropLeft = QtWidgets.QSpinBox(self.tab)
        self.spinBoxCropLeft.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBoxCropLeft.setMaximum(999999)
        self.spinBoxCropLeft.setObjectName("spinBoxCropLeft")
        self.combLineEditLabelCropLeft.addWidget(self.spinBoxCropLeft)
        self.cropLeftType = QtWidgets.QComboBox(self.tab)
        self.cropLeftType.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cropLeftType.setObjectName("cropLeftType")
        self.cropLeftType.addItem("")
        self.cropLeftType.addItem("")
        self.combLineEditLabelCropLeft.addWidget(self.cropLeftType)
        self.verticalLayout.addLayout(self.combLineEditLabelCropLeft)
        self.combLineEditLabelCropRight = QtWidgets.QHBoxLayout()
        self.combLineEditLabelCropRight.setSpacing(6)
        self.combLineEditLabelCropRight.setObjectName("combLineEditLabelCropRight")
        self.cropRightLabel = QtWidgets.QLabel(self.tab)
        self.cropRightLabel.setMaximumSize(QtCore.QSize(52, 20))
        self.cropRightLabel.setObjectName("cropRightLabel")
        self.combLineEditLabelCropRight.addWidget(self.cropRightLabel)
        self.spinBoxCropRight = QtWidgets.QSpinBox(self.tab)
        self.spinBoxCropRight.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBoxCropRight.setMaximum(999999)
        self.spinBoxCropRight.setObjectName("spinBoxCropRight")
        self.combLineEditLabelCropRight.addWidget(self.spinBoxCropRight)
        self.cropRightType = QtWidgets.QComboBox(self.tab)
        self.cropRightType.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cropRightType.setObjectName("cropRightType")
        self.cropRightType.addItem("")
        self.cropRightType.addItem("")
        self.combLineEditLabelCropRight.addWidget(self.cropRightType)
        self.verticalLayout.addLayout(self.combLineEditLabelCropRight)
        self.checkBoxLockTB = QtWidgets.QCheckBox(self.tab)
        self.checkBoxLockTB.setObjectName("checkBoxLockTB")
        self.verticalLayout.addWidget(self.checkBoxLockTB)
        self.combLineEditLabelCropTop = QtWidgets.QHBoxLayout()
        self.combLineEditLabelCropTop.setSpacing(6)
        self.combLineEditLabelCropTop.setObjectName("combLineEditLabelCropTop")
        self.cropTopLabel = QtWidgets.QLabel(self.tab)
        self.cropTopLabel.setMaximumSize(QtCore.QSize(52, 20))
        self.cropTopLabel.setObjectName("cropTopLabel")
        self.combLineEditLabelCropTop.addWidget(self.cropTopLabel)
        self.spinBoxCropTop = QtWidgets.QSpinBox(self.tab)
        self.spinBoxCropTop.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBoxCropTop.setMaximum(999999)
        self.spinBoxCropTop.setObjectName("spinBoxCropTop")
        self.combLineEditLabelCropTop.addWidget(self.spinBoxCropTop)
        self.cropTopType = QtWidgets.QComboBox(self.tab)
        self.cropTopType.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cropTopType.setObjectName("cropTopType")
        self.cropTopType.addItem("")
        self.cropTopType.addItem("")
        self.combLineEditLabelCropTop.addWidget(self.cropTopType)
        self.verticalLayout.addLayout(self.combLineEditLabelCropTop)
        self.combLineEditLabelCropBottom = QtWidgets.QHBoxLayout()
        self.combLineEditLabelCropBottom.setSpacing(6)
        self.combLineEditLabelCropBottom.setObjectName("combLineEditLabelCropBottom")
        self.cropBottomLabel = QtWidgets.QLabel(self.tab)
        self.cropBottomLabel.setMaximumSize(QtCore.QSize(52, 20))
        self.cropBottomLabel.setObjectName("cropBottomLabel")
        self.combLineEditLabelCropBottom.addWidget(self.cropBottomLabel)
        self.spinBoxCropBottom = QtWidgets.QSpinBox(self.tab)
        self.spinBoxCropBottom.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBoxCropBottom.setMaximum(999999)
        self.spinBoxCropBottom.setObjectName("spinBoxCropBottom")
        self.combLineEditLabelCropBottom.addWidget(self.spinBoxCropBottom)
        self.cropBottomType = QtWidgets.QComboBox(self.tab)
        self.cropBottomType.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cropBottomType.setObjectName("cropBottomType")
        self.cropBottomType.addItem("")
        self.cropBottomType.addItem("")
        self.combLineEditLabelCropBottom.addWidget(self.cropBottomType)
        self.verticalLayout.addLayout(self.combLineEditLabelCropBottom)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.graphicsViewFullImage = QtWidgets.QGraphicsView(self.tab)
        self.graphicsViewFullImage.setFrameShape(QtWidgets.QFrame.NoFrame)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewFullImage.setBackgroundBrush(brush)
        self.graphicsViewFullImage.setObjectName("graphicsViewFullImage")
        self.horizontalLayout.addWidget(self.graphicsViewFullImage)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Rast_label_1 = QtWidgets.QLabel(self.tab_2)
        self.Rast_label_1.setObjectName("Rast_label_1")
        self.verticalLayout_3.addWidget(self.Rast_label_1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.spinBoxDesiredSize = QtWidgets.QSpinBox(self.tab_2)
        self.spinBoxDesiredSize.setMaximum(99999999)
        self.spinBoxDesiredSize.setProperty("value", 401)
        self.spinBoxDesiredSize.setObjectName("spinBoxDesiredSize")
        self.horizontalLayout_5.addWidget(self.spinBoxDesiredSize)
        self.comboBoxDesiredAxis = QtWidgets.QComboBox(self.tab_2)
        self.comboBoxDesiredAxis.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBoxDesiredAxis.setObjectName("comboBoxDesiredAxis")
        self.comboBoxDesiredAxis.addItem("")
        self.comboBoxDesiredAxis.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBoxDesiredAxis)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBoxPDFMarginX = QtWidgets.QSpinBox(self.tab_2)
        self.spinBoxPDFMarginX.setProperty("value", 5)
        self.spinBoxPDFMarginX.setObjectName("spinBoxPDFMarginX")
        self.horizontalLayout_3.addWidget(self.spinBoxPDFMarginX)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.spinBoxPDFMarginY = QtWidgets.QSpinBox(self.tab_2)
        self.spinBoxPDFMarginY.setProperty("value", 5)
        self.spinBoxPDFMarginY.setObjectName("spinBoxPDFMarginY")
        self.horizontalLayout_9.addWidget(self.spinBoxPDFMarginY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.comboBoxMarking = QtWidgets.QComboBox(self.tab_2)
        self.comboBoxMarking.setObjectName("comboBoxMarking")
        self.comboBoxMarking.addItem("")
        self.comboBoxMarking.addItem("")
        self.comboBoxMarking.addItem("")
        self.comboBoxMarking.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBoxMarking)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBoxPageRotation = QtWidgets.QComboBox(self.tab_2)
        self.comboBoxPageRotation.setObjectName("comboBoxPageRotation")
        self.comboBoxPageRotation.addItem("")
        self.comboBoxPageRotation.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxPageRotation)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.pushButtonCreatePDF = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonCreatePDF.setObjectName("pushButtonCreatePDF")
        self.verticalLayout_3.addWidget(self.pushButtonCreatePDF)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.graphicsViewPDFImage = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsViewPDFImage.setFrameShape(QtWidgets.QFrame.NoFrame)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewPDFImage.setBackgroundBrush(brush)
        self.graphicsViewPDFImage.setObjectName("graphicsViewPDFImage")
        self.horizontalLayout_2.addWidget(self.graphicsViewPDFImage)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonChooseImage.setText(_translate("MainWindow", "Choose image"))
        self.label_5.setText(_translate("MainWindow", "Crop settings:"))
        self.checkBoxLockLR.setText(_translate("MainWindow", "Lock left/right"))
        self.cropLeftLabel.setText(_translate("MainWindow", "Crop Left"))
        self.cropLeftType.setItemText(0, _translate("MainWindow", "px"))
        self.cropLeftType.setItemText(1, _translate("MainWindow", "%"))
        self.cropRightLabel.setText(_translate("MainWindow", "Crop Right"))
        self.cropRightType.setItemText(0, _translate("MainWindow", "px"))
        self.cropRightType.setItemText(1, _translate("MainWindow", "%"))
        self.checkBoxLockTB.setText(_translate("MainWindow", "Lock top/bottom"))
        self.cropTopLabel.setText(_translate("MainWindow", "Crop Top"))
        self.cropTopType.setItemText(0, _translate("MainWindow", "px"))
        self.cropTopType.setItemText(1, _translate("MainWindow", "%"))
        self.cropBottomLabel.setText(_translate("MainWindow", "Crop Bottom"))
        self.cropBottomType.setItemText(0, _translate("MainWindow", "px"))
        self.cropBottomType.setItemText(1, _translate("MainWindow", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.Rast_label_1.setText(_translate("MainWindow", "Rasterizer settings:"))
        self.label_3.setText(_translate("MainWindow", "Desired size (mm)"))
        self.comboBoxDesiredAxis.setItemText(0, _translate("MainWindow", "heigh"))
        self.comboBoxDesiredAxis.setItemText(1, _translate("MainWindow", "wide"))
        self.label.setText(_translate("MainWindow", "Margin x (mm)"))
        self.label_9.setText(_translate("MainWindow", "Margin y (mm)"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.comboBoxMarking.setItemText(0, _translate("MainWindow", "Half cross"))
        self.comboBoxMarking.setItemText(1, _translate("MainWindow", "Full cross"))
        self.comboBoxMarking.setItemText(2, _translate("MainWindow", "Full line"))
        self.comboBoxMarking.setItemText(3, _translate("MainWindow", "No marking"))
        self.label_2.setText(_translate("MainWindow", "Page layout"))
        self.comboBoxPageRotation.setItemText(0, _translate("MainWindow", "vertical"))
        self.comboBoxPageRotation.setItemText(1, _translate("MainWindow", "horizontal"))
        self.pushButtonCreatePDF.setText(_translate("MainWindow", "Create PDF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

