# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 602)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setMaximumSize(QtCore.QSize(180, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-3, 0, 171, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(5, 20, 5, 20)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.checkBoxLockLR = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxLockLR.setObjectName("checkBoxLockLR")
        self.verticalLayout.addWidget(self.checkBoxLockLR)
        self.combLineEditLabelCropLeft = QtWidgets.QHBoxLayout()
        self.combLineEditLabelCropLeft.setContentsMargins(-1, 0, -1, 0)
        self.combLineEditLabelCropLeft.setSpacing(6)
        self.combLineEditLabelCropLeft.setObjectName("combLineEditLabelCropLeft")
        self.cropLeftLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cropLeftLabel.setMaximumSize(QtCore.QSize(52, 20))
        self.cropLeftLabel.setObjectName("cropLeftLabel")
        self.combLineEditLabelCropLeft.addWidget(self.cropLeftLabel)
        self.spinBoxCropLeft = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxCropLeft.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBoxCropLeft.setMaximum(999999)
        self.spinBoxCropLeft.setObjectName("spinBoxCropLeft")
        self.combLineEditLabelCropLeft.addWidget(self.spinBoxCropLeft)
        self.cropLeftType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cropLeftType.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cropLeftType.setObjectName("cropLeftType")
        self.cropLeftType.addItem("")
        self.cropLeftType.addItem("")
        self.combLineEditLabelCropLeft.addWidget(self.cropLeftType)
        self.verticalLayout.addLayout(self.combLineEditLabelCropLeft)
        self.combLineEditLabelCropRight = QtWidgets.QHBoxLayout()
        self.combLineEditLabelCropRight.setSpacing(6)
        self.combLineEditLabelCropRight.setObjectName("combLineEditLabelCropRight")
        self.cropRightLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cropRightLabel.setMaximumSize(QtCore.QSize(52, 20))
        self.cropRightLabel.setObjectName("cropRightLabel")
        self.combLineEditLabelCropRight.addWidget(self.cropRightLabel)
        self.spinBoxCropRight = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxCropRight.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBoxCropRight.setMaximum(999999)
        self.spinBoxCropRight.setObjectName("spinBoxCropRight")
        self.combLineEditLabelCropRight.addWidget(self.spinBoxCropRight)
        self.cropRightType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cropRightType.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cropRightType.setObjectName("cropRightType")
        self.cropRightType.addItem("")
        self.cropRightType.addItem("")
        self.combLineEditLabelCropRight.addWidget(self.cropRightType)
        self.verticalLayout.addLayout(self.combLineEditLabelCropRight)
        self.checkBoxLockTB = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxLockTB.setObjectName("checkBoxLockTB")
        self.verticalLayout.addWidget(self.checkBoxLockTB)
        self.combLineEditLabelCropTop = QtWidgets.QHBoxLayout()
        self.combLineEditLabelCropTop.setSpacing(6)
        self.combLineEditLabelCropTop.setObjectName("combLineEditLabelCropTop")
        self.cropTopLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cropTopLabel.setMaximumSize(QtCore.QSize(52, 20))
        self.cropTopLabel.setObjectName("cropTopLabel")
        self.combLineEditLabelCropTop.addWidget(self.cropTopLabel)
        self.spinBoxCropTop = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxCropTop.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBoxCropTop.setMaximum(999999)
        self.spinBoxCropTop.setObjectName("spinBoxCropTop")
        self.combLineEditLabelCropTop.addWidget(self.spinBoxCropTop)
        self.cropTopType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cropTopType.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cropTopType.setObjectName("cropTopType")
        self.cropTopType.addItem("")
        self.cropTopType.addItem("")
        self.combLineEditLabelCropTop.addWidget(self.cropTopType)
        self.verticalLayout.addLayout(self.combLineEditLabelCropTop)
        self.combLineEditLabelCropBottom = QtWidgets.QHBoxLayout()
        self.combLineEditLabelCropBottom.setSpacing(6)
        self.combLineEditLabelCropBottom.setObjectName("combLineEditLabelCropBottom")
        self.cropBottomLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cropBottomLabel.setMaximumSize(QtCore.QSize(52, 20))
        self.cropBottomLabel.setObjectName("cropBottomLabel")
        self.combLineEditLabelCropBottom.addWidget(self.cropBottomLabel)
        self.spinBoxCropBottom = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxCropBottom.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBoxCropBottom.setMaximum(999999)
        self.spinBoxCropBottom.setObjectName("spinBoxCropBottom")
        self.combLineEditLabelCropBottom.addWidget(self.spinBoxCropBottom)
        self.cropBottomType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cropBottomType.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cropBottomType.setObjectName("cropBottomType")
        self.cropBottomType.addItem("")
        self.cropBottomType.addItem("")
        self.combLineEditLabelCropBottom.addWidget(self.cropBottomType)
        self.verticalLayout.addLayout(self.combLineEditLabelCropBottom)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBoxPDFMarginX = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxPDFMarginX.setProperty("value", 5)
        self.spinBoxPDFMarginX.setObjectName("spinBoxPDFMarginX")
        self.horizontalLayout_3.addWidget(self.spinBoxPDFMarginX)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.spinBoxPDFMarginY = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxPDFMarginY.setProperty("value", 5)
        self.spinBoxPDFMarginY.setObjectName("spinBoxPDFMarginY")
        self.horizontalLayout_9.addWidget(self.spinBoxPDFMarginY)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBoxPageRotation = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxPageRotation.setObjectName("comboBoxPageRotation")
        self.comboBoxPageRotation.addItem("")
        self.comboBoxPageRotation.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxPageRotation)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.spinBoxDesiredSize = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxDesiredSize.setMaximum(99999999)
        self.spinBoxDesiredSize.setProperty("value", 200)
        self.spinBoxDesiredSize.setObjectName("spinBoxDesiredSize")
        self.horizontalLayout_5.addWidget(self.spinBoxDesiredSize)
        self.comboBoxDesiredAxis = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxDesiredAxis.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBoxDesiredAxis.setObjectName("comboBoxDesiredAxis")
        self.comboBoxDesiredAxis.addItem("")
        self.comboBoxDesiredAxis.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBoxDesiredAxis)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.comboBoxMarking = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxMarking.setObjectName("comboBoxMarking")
        self.comboBoxMarking.addItem("")
        self.comboBoxMarking.addItem("")
        self.comboBoxMarking.addItem("")
        self.comboBoxMarking.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBoxMarking)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pushButtonCreatePDF = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonCreatePDF.setObjectName("pushButtonCreatePDF")
        self.verticalLayout.addWidget(self.pushButtonCreatePDF)
        self.horizontalLayout.addWidget(self.widget)
        self.mainImageLabel = QtWidgets.QLabel(self.centralWidget)
        self.mainImageLabel.setObjectName("mainImageLabel")
        self.horizontalLayout.addWidget(self.mainImageLabel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1113, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Crop settings:"))
        self.checkBoxLockLR.setText(_translate("MainWindow", "Lock left/right"))
        self.cropLeftLabel.setText(_translate("MainWindow", "Crop Left"))
        self.cropLeftType.setItemText(0, _translate("MainWindow", "px"))
        self.cropLeftType.setItemText(1, _translate("MainWindow", "%"))
        self.cropRightLabel.setText(_translate("MainWindow", "Crop Right"))
        self.cropRightType.setItemText(0, _translate("MainWindow", "px"))
        self.cropRightType.setItemText(1, _translate("MainWindow", "%"))
        self.checkBoxLockTB.setText(_translate("MainWindow", "Lock top/bottom"))
        self.cropTopLabel.setText(_translate("MainWindow", "Crop Top"))
        self.cropTopType.setItemText(0, _translate("MainWindow", "px"))
        self.cropTopType.setItemText(1, _translate("MainWindow", "%"))
        self.cropBottomLabel.setText(_translate("MainWindow", "Crop Bottom"))
        self.cropBottomType.setItemText(0, _translate("MainWindow", "px"))
        self.cropBottomType.setItemText(1, _translate("MainWindow", "%"))
        self.label_6.setText(_translate("MainWindow", "Rasterizer settings:"))
        self.label.setText(_translate("MainWindow", "Margin x (mm)"))
        self.label_9.setText(_translate("MainWindow", "Margin y (mm)"))
        self.label_2.setText(_translate("MainWindow", "Page layout"))
        self.comboBoxPageRotation.setItemText(0, _translate("MainWindow", "vertical"))
        self.comboBoxPageRotation.setItemText(1, _translate("MainWindow", "horizontal"))
        self.label_3.setText(_translate("MainWindow", "Desired size (mm)"))
        self.comboBoxDesiredAxis.setItemText(0, _translate("MainWindow", "wide"))
        self.comboBoxDesiredAxis.setItemText(1, _translate("MainWindow", "heigh"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.comboBoxMarking.setItemText(0, _translate("MainWindow", "Half cross"))
        self.comboBoxMarking.setItemText(1, _translate("MainWindow", "Full cross"))
        self.comboBoxMarking.setItemText(2, _translate("MainWindow", "Full line"))
        self.comboBoxMarking.setItemText(3, _translate("MainWindow", "No marking"))
        self.pushButtonCreatePDF.setText(_translate("MainWindow", "Create PDF"))
        self.mainImageLabel.setText(_translate("MainWindow", "TextLabel"))

